### ISSUE TITLE
Update my shitty old pom file

### ISSUE THREAD

**Issue by sgdc3** [TekkitCommando/Empirecraft#1]
I can do it tomorrow if you want ;)

**Comment by TekkitCommando** [comment]
sure that would be awesome ;D

**Comment by sgdc3** [comment]
What's your IDE? Just to setup the pom correctly ;)

**Comment by TekkitCommando** [comment]
I go back and forth between Eclipse and IntelliJ xD

**Comment by sgdc3** [comment]
Like me, so this pom should work fine! :D

**Comment by sgdc3** [comment]
Check my PR

**Comment by TekkitCommando** [comment]
Ok

**Comment by sgdc3** [comment]
I think we can close this ;)

**Comment by TekkitCommando** [comment]
Ah yes xD
